### ISSUE TITLE
Project Settings: Create basic async project settings service

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#509]
As an extension developer, I want to be able to access project settings like Biblical Terms list on the PAPI so I can develop effectively.

----

We need a project settings service that allows any PSI to validate project settings before saving (PSI actually handles project settings, and PDP passes through to PSI):

- [x] Main process should have project settings service host that has a network object. Other processes imitate and access with project settings service. `papi.projectSettings`
  - [x] Maintain list of all project settings' default values (hard-coded; we will load from extensions in #721)
  - [x] Create a new `ProjectSettingTypes` shared type in `papi-shared-types` along the same lines as `SettingTypes`
    - [x] Include some real settings - books present, language, versification
  - [x] `papi.projectSettings.isValid(newValue, currentValue, key, allChanges, projectType)` - simply returns true. This is just a placeholder for now that will be implemented later - see #511 for information on what `allChanges` is
  - [x] `papi.projectSettings.getDefault(key, projectType)` - provides the default value for the project setting
    - If project setting default is provided in extensions or built into core (though for now the list is just built into core as mentioned above), returns project setting default
    - If project setting default is not provided anywhere, throws
- [x] PDP needs a new data type in its MandatoryDataTypes `Setting: DataProviderDataTypes<ProjectSettingNames, ProjectSettingTypes, ProjectSettingTypes>`. Explain that this should just pass through to the PSI. It also needs `resetSetting(key)` which should also pass through to the PSI
- [x] PSI needs a new MandatoryDataTypes type `Setting: DataProviderDataTypes<{ projectId: string, key: ProjectSettingNames }, ProjectSettingTypes, ProjectSettingTypes>`. Explain that the `setSetting` function needs to run `papi.projectSettings.isValid` before accepting the new setting. Explain that the `getSetting` function should return the value for a setting if set and should otherwise run `papi.projectSettings.getDefault` to get the default value if it does not have a value for the setting. Explain that PSI also needs a `resetSetting(projectId, key)` function that deletes the value at the key and sends a setting update event
- [x] Create `useProjectSetting(projectDataProviderSource, key, defaultValue)`-ish hook that looks suspiciously similar to `useSetting` from #502. Maybe can just use `useProjectData` internally
- PSI does the actual persisting of project settings

Notes:
- keeping track of provided project settings and defaults is in #721 
- the actual validators for project settings will be dealt with in #511
- the components for editing these project settings will be dealt with in #510

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

**Comment by tjcouch-sil** [comment]
I discovered that [you can use `keyof`](https://www.typescriptlang.org/play?#code/PTAECIAUBFPUAuBPADgUwM4FgBQBLAOwTQCcAzAQwGM1QBlBAVzLNAG9dQvQByBAC0IBzHgC5QBRgFsARqQDcnbn0EEhAJjGgMCEsMU4AvrlwgIkOgEl4ydNnxFSlGvSYt17JVxXCtbUABuFAA24pKypKCGBty8AsKa4v5Bodq6wlExyvFqAMx+gSHiPBQYACZkPJm4xjimYABKaGVoVMEUemqgAO4A9iQA1hgANNq9oFKMwQh4KMG0aAAexAQYeL2roFQUBKAtbR20ArQYFFK0FpaIqGi4hMTk1LQMzGQeHDixPmoFKWHSchI1SMJhwZEYBCoMw2oCEaAQLxYAB5EWQANJoJCgJYrMoYUADTG9ViogB8AApCUhxKiMUgAJQ0txkADatMxAF1PJ9uCR4YwSLseDwDLVcFQNjpEABGUAAXlh8NR5O+InpBglqwQiA8CrhCOZKpyGh46tB4Mh0N2+tR6hRzLp2OWaAIeIJRJJzIpVKZrzpjNcr3UbIdnO5sT5TEFvBFNVBZku1zsWx2EwoKFAZBIvSkoBgkHdSHsmqlGHUCFleqVzPURtUao1ku1ZYQusVBqDdYSpoM9VAAFkKEg5D0TvxelMymnCXmrPj+BQAkd+Gg8EDet1dlJ0+gp7ZaDIsShswArVoIAAqNwAhEA) one interface to index against another interface as long as the other interface has all the keys of the one interface. TypeScript is magic. As such, I think we can coordinate PDPs and PSIs according to `projectType` as the key.
